name: Verificar IP Público, Abrir Porta de Teste e Aguardar Conexão

on:
  push:
    branches:
      - main  # ou o nome da sua branch principal

jobs:
  check_ip_and_open_port:
    runs-on: ubuntu-latest  # Ambiente Linux

    steps:
    - uses: actions/checkout@v2  # Clona o repositório

    - name: Verificar IP público
      run: |
        ip=$(curl -s ifconfig.me)
        echo "O IP público é: $ip"

    - name: Instalar Netcat (nc)
      run: sudo apt-get install -y netcat

    - name: Abrir porta 5151 no firewall
      run: sudo ufw allow 5151

    - name: Abrir porta de teste e aguardar conexão
      run: |
        # Iniciar Netcat em um subshell para que o loop não seja bloqueado
        ( nc -l 5151 & )
        # Loop para manter o Netcat em execução
        while true; do
          sleep 5000  # Aguardar 5000 segundos (aproximadamente 1 hora e 23 minutos)
        done
