name: Verificar IP Público, Abrir Porta de Teste e Aguardar Conexão

on:
  push:
    branches:
      - main  # ou o nome da sua branch principal

jobs:
  check_ip_and_open_port:
    runs-on: ubuntu-latest  # Ambiente Linux

    steps:
    - uses: actions/checkout@v2  # Clona o repositório

    - name: Verificar IP público
      run: |
        ip=$(curl -s ifconfig.me)
        echo "O IP público é: $ip"

    - name: Instalar Netcat (nc)
      run: sudo apt-get install -y netcat

    - name: Abrir porta de teste
      run: |
        nc -l 5151 &
        echo "Porta de teste 5151 aberta"

    - name: Aguardar conexão
      run: |
        while ! nc -z localhost 5151; do
          sleep 1
        done
        echo "Conexão estabelecida com sucesso!"
